let suggestions = [
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in THML & CSS",
    "How to learn HTML & CSS",
    "How to became FreeLancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube ChannelMergerNode",
    "What does HTML stands for?",
    "What does CSS stands for?",
]